user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

g_plateform:
    resource: "@GPlateformBundle/Resources/config/routing.yml"
    prefix:   /plateform

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
