g_plateform_home:
    path:    /{page}
    defaults:
        _controller: GPlateformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

g_plateform_view:
    path:    /article/{id}
    defaults:
        _controller: GPlateformBundle:Advert:view
    requirements: 
        id: \d+

g_plateform_add:
    path:    /add
    defaults:
         _controller: GPlateformBundle:Advert:add

g_plateform_showDelete:
    path:    /showDelete
    defaults:
         _controller: GPlateformBundle:Advert:showDelete

g_plateform_edit:
    path:    /edit/{id}
    defaults: 
        _controller: GPlateformBundle:Advert:edit
    requirements:
        id: \d+

g_plateform_delete:
    path:    /delete/{id}
    defaults:
        _controller: GPlateformBundle:Advert:delete
    requirements:
        id: \d+

g_plateform_songs:
    path: /songs
    defaults:
        _controller: GPlateformBundle:Advert:songs

g_plateform_art:
    path: /art
    defaults:
        _controller: GPlateformBundle:Advert:art

g_plateform_news:
    path: /news
    defaults:
        _controller: GPlateformBundle:Advert:news

g_plateform_contact:
    path: /contact
    defaults:
        _controller: GPlateformBundle:Advert:contact

g_plateform_about:
    path: /about
    defaults:
        _controller: GPlateformBundle:Advert:about